---

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - '*.*'
      - '*.*.*'
  pull_request: null

name: MSSQL

jobs:
  phpunit:
    uses: cycle/gh-actions/.github/workflows/db-mssql.yml@master
    with:
      php: '["8.1","8.2","8.3"]'

...
